name: Adventures In Agriculture
favicon: null
layout_spectrum: 0.76643
typography_spectrum: 0.4374
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5496bb'
    - '#9bbacd'
    - '#353e53'
    - '#8a6a4d'
    - '#a32021'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
