name: Adventures In Agriculture
favicon: null
layout_spectrum: 0.46815
typography_spectrum: 0.74016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5496bb'
    - '#9bbacd'
    - '#353e53'
    - '#8a6a4d'
    - '#a32021'
  brandStrength: 0.2790338739287108
  lightness: 0.8129471994470805
  saturation: 0.43012120155617595
  rhythmicContrast: 0.19252731930464506
purpose: []
