name: Adventures In Agriculture
favicon: null
layout_spectrum: 0.9394437693990767
typography_spectrum: 0.15403314982540905
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2790338739287108
  lightness: 0.8129471994470805
  saturation: 0.43012120155617595
  rhythmicContrast: 0.19252731930464506
purpose: []
